/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import Conexcion.cliente;
import ConexionBD.CultivosCompara;
import ConexionBD.SQLUsuarios;
import ConexionBD.Usuarios;
import proyecto.pnlInformes;
import proyecto.pnlRegPlantas;
import proyecto.pnlRegistro;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.beans.Observable;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import static proyecto.VentanaCliente1.c;

/**
 *
 * @author Acer Nitro 5
 */
public class IntAdmin extends javax.swing.JFrame  {

    String nombreProductoActual;
    CardLayout vista;
    pnlInformes pnlinformes = new pnlInformes();
    pnlRegistro pnlregistro = new pnlRegistro();
    pnlGraficas1 pnlGraficas13 = new pnlGraficas1();
    public static ArrayList<CultivosCompara> CultivosCompa;
    public static double[] precios1 = new double[4];
    SQLUsuarios modSQL;
    //private Thread t;
    Usuarios usu;

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel[] pane, JPanel[] indicators) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(0, 38, 28));

        }
        for (int i = 0; i < indicators.length; i++) {
            indicators[i].setBackground(new Color(0, 38, 28));
        }

    }

//*********************************************************************************************
    public IntAdmin(SQLUsuarios sql, Usuarios us) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/holi.jpeg")).getImage());
        this.modSQL = sql;
        this.CultivosCompa = modSQL.CultivosCOmpa();
        this.usu = us;
//        try {
//            c = new cliente(5000, "54.161.133.42");
//            //c = new cliente(5000, "192.168.0.21");
//        } catch (IOException ex) {
//            JOptionPane.showMessageDialog(this, "Servidor no encontrado");
//            System.exit(0);
//        }
//        c.addObserver(this);
//        t = new Thread(c);
//        t.start();
//        this.setLocationRelativeTo(null);

        vista = (CardLayout) pnlPrincipal.getLayout();

        setColor(btnbusqueda);
        indbusqueda.setBackground(new Color(39, 86, 43));
        resetColor(new JPanel[]{btnregistrar}, new JPanel[]{indregistrar});

        pnlPrincipal.add(pnlinformes, "busqueda");
        vista.show(pnlPrincipal, "busqueda");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }

    public IntAdmin() {

    }
//*********************************************************************************************

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnregistrar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        indregistrar = new javax.swing.JPanel();
        btnbusqueda = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        indbusqueda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(22, 128, 57));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intAdmin/minimizarR.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 60, 50));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intAdmin/cerrarR.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel21MouseMoved(evt);
            }
        });
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 60, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 800, 50));

        jPanel1.setBackground(new java.awt.Color(0, 38, 28));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnregistrar.setBackground(new java.awt.Color(0, 38, 28));
        btnregistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnregistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnregistrarMousePressed(evt);
            }
        });
        btnregistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Registrar");
        btnregistrar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        indregistrar.setBackground(new java.awt.Color(0, 38, 28));
        indregistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btnregistrar.add(indregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jPanel1.add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 100, 60));

        btnbusqueda.setBackground(new java.awt.Color(0, 38, 28));
        btnbusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnbusquedaMousePressed(evt);
            }
        });
        btnbusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Búsqueda");
        btnbusqueda.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        indbusqueda.setBackground(new java.awt.Color(0, 38, 28));
        indbusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btnbusqueda.add(indbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jPanel1.add(btnbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoicon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 750));

        pnlPrincipal.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 800, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistrarMousePressed
        setColor(btnregistrar);
        indregistrar.setBackground(new Color(39, 86, 43));
        resetColor(new JPanel[]{btnbusqueda}, new JPanel[]{indbusqueda});

        pnlPrincipal.add(pnlregistro, "registro");
        vista.show(pnlPrincipal, "registro");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();

    }//GEN-LAST:event_btnregistrarMousePressed

    private void btnbusquedaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbusquedaMousePressed

        setColor(btnbusqueda);
        indbusqueda.setBackground(new Color(39, 86, 43));
        resetColor(new JPanel[]{btnregistrar}, new JPanel[]{indregistrar});

        pnlPrincipal.add(pnlinformes, "busqueda");
        vista.show(pnlPrincipal, "busqueda");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();


    }//GEN-LAST:event_btnbusquedaMousePressed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseMoved

    }//GEN-LAST:event_jLabel21MouseMoved

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "Exit", dialog);
        if (result == 0) {
            modSQL.Salida(usu);
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited

    }//GEN-LAST:event_jLabel21MouseExited

    int xx, yy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        modSQL.Salida(usu);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnbusqueda;
    private javax.swing.JPanel btnregistrar;
    private javax.swing.JPanel indbusqueda;
    private javax.swing.JPanel indregistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables

//    @Override
//    public void update(java.util.Observable o, Object arg) {
//
//        if (arg instanceof String) {
//            nombreProductoActual = (String) arg;
//        } else {
//            double valor = (double) arg;
//            switch (nombreProductoActual) {
//                case "Zanahoria":
//                    this.precios1[0] = (double) arg;
//                    pnlGraficas1.NombreCultiZana.setText(nombreProductoActual + " X 500g");
//                    this.precios1[0] = Math.round(this.precios1[0] * 100) / 100d;
//                    pnlGraficas1.PrecioCulviZana.setText("$" + String.valueOf(this.precios1[0]));
//                    if (this.precios1[0] != this.CultivosCompa.get(0).getPrecio()) {
//                        if (this.precios1[0] > this.CultivosCompa.get(0).getPrecio()) {
//                            pnlGraficas1.OfertaZana.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Sube.png")));
//                            pnlGraficas1.DemandaZana.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Baja.png")));
//                        } else {
//                            pnlGraficas1.OfertaZana.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Baja.png")));
//                            pnlGraficas1.DemandaZana.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Sube.png")));
//                        }
//                    } else {
//                        pnlGraficas1.DemandaZana.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Igual.png")));
//                        pnlGraficas1.OfertaZana.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Igual.png")));
//                    }
//                    break;
//                case "Maíz":
//                    this.precios1[1] = (double) arg;
//                    pnlGraficas1.NombreCultiMaiz.setText(nombreProductoActual + " X Kg");
//                    this.precios1[1] = Math.round(this.precios1[1] * 100) / 100d;
//                    pnlGraficas1.PrecioCulviMaiz.setText("$" + String.valueOf(this.precios1[1]));
//                    if (this.precios1[1] != this.CultivosCompa.get(1).getPrecio()) {
//                        if (this.precios1[1] > this.CultivosCompa.get(1).getPrecio()) {
//                            pnlGraficas1.OfertaMaiz.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Sube.png")));
//                            pnlGraficas1.DemandaMaiz.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Baja.png")));
//                        } else {
//                            pnlGraficas1.OfertaMaiz.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Baja.png")));
//                            pnlGraficas1.DemandaMaiz.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Sube.png")));
//                        }
//                    } else {
//                        pnlGraficas1.DemandaMaiz.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Igual.png")));
//                        pnlGraficas1.OfertaMaiz.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Igual.png")));
//                    }
//                    break;
//                case "Papa":
//                    this.precios1[2] = (double) arg;
//                    pnlGraficas1.NombreCultipapa.setText(nombreProductoActual + " X Kg");
//                    this.precios1[2] = Math.round(this.precios1[2] * 100) / 100d;
//                    pnlGraficas1.PrecioCulvipapa.setText("$" + String.valueOf(this.precios1[2]));
//                    if (this.precios1[2] != this.CultivosCompa.get(2).getPrecio()) {
//                        if (this.precios1[2] > this.CultivosCompa.get(2).getPrecio()) {
//                            pnlGraficas1.Ofertapapa.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Sube.png")));
//                            pnlGraficas1.Demandapapa.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Baja.png")));
//                        } else {
//                            pnlGraficas1.Ofertapapa.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Baja.png")));
//                            pnlGraficas1.Demandapapa.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Sube.png")));
//                        }
//                    } else {
//                        pnlGraficas1.Demandapapa.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Igual.png")));
//                        pnlGraficas1.Ofertapapa.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Igual.png")));
//                    }
//                    break;
//                case "Tomate":
//                    this.precios1[3] = (double) arg;
//                    pnlGraficas1.NombreCultiToma.setText(nombreProductoActual + " X 500g");
//                    this.precios1[3] = Math.round(this.precios1[3] * 100) / 100d;
//                    pnlGraficas1.PrecioCulviToma.setText("$" + String.valueOf(this.precios1[3]));
//                    if (this.precios1[3] != this.CultivosCompa.get(3).getPrecio()) {
//                        if (this.precios1[3] > this.CultivosCompa.get(3).getPrecio()) {
//                            pnlGraficas1.OfertaToma.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Sube.png")));
//                            pnlGraficas1.DemandaToma.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Baja.png")));
//                        } else {
//                            pnlGraficas1.OfertaToma.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Baja.png")));
//                            pnlGraficas1.DemandaToma.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Sube.png")));
//                        }
//                    } else {
//                        pnlGraficas1.DemandaToma.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Igual.png")));
//                        pnlGraficas1.OfertaToma.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Igual.png")));
//                    }
//                    double in3 = -999;
//                    int sd3 = 0;
//                    for (int i = 0; i < 4; i++) {
//                        if (this.precios1[i] > in3) {
//                            in3 = this.precios1[i];
//                            sd3 = i;
//                        }
//                    }
//                    pnlGraficas1.Recomentdacion.setText("<html>Cosechar " + this.CultivosCompa.get(sd3).getNombreCultivo() + " \n"
//                            + "con un valor de $" + this.precios1[sd3] + "</html>");
//                    break;
//
//            }
//        }
//    }
}
