/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import ConexionBD.Cultivo;
import ConexionBD.Estados;
import ConexionBD.Hash;
import ConexionBD.SQLUsuarios;
import ConexionBD.TipoUsuarios;
import ConexionBD.Usuarios;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Loginv extends javax.swing.JFrame {

    public Loginv() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/holi.jpeg")).getImage());
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnombreusuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtcontraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton3.setText("Registrate ahora!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agro-Learning");
        setBackground(new java.awt.Color(0, 153, 51));
        setMinimumSize(new java.awt.Dimension(1188, 580));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(189, 235, 239));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(18, 85, 103));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(18, 85, 103));
        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel5.setBackground(new java.awt.Color(18, 85, 103));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(18, 85, 103));
        jLabel5.setText("Usuario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/llave.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 30, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UserLog.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 30, 30));

        txtnombreusuario.setBackground(new java.awt.Color(189, 235, 239));
        txtnombreusuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtnombreusuario.setToolTipText("");
        txtnombreusuario.setBorder(null);
        txtnombreusuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtnombreusuarioMouseMoved(evt);
            }
        });
        txtnombreusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnombreusuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtnombreusuarioMouseExited(evt);
            }
        });
        jPanel1.add(txtnombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 200, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 250, 10));

        txtcontraseña.setBackground(new java.awt.Color(189, 235, 239));
        txtcontraseña.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtcontraseña.setForeground(new java.awt.Color(51, 51, 51));
        txtcontraseña.setBorder(null);
        txtcontraseña.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtcontraseñaMouseMoved(evt);
            }
        });
        txtcontraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcontraseñaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtcontraseñaMouseExited(evt);
            }
        });
        jPanel1.add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 200, 40));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 250, 10));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enter.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enterON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enterON.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enterON.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 130, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, 90));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel9MouseMoved(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 60, 50));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 60, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 580));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intAdmin/fondoIcioSesion.jpg"))); // NOI18N
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel11MouseDragged(evt);
            }
        });
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 868, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        /*
        this.dispose();
        Registro v = new Registro();       
        v.setVisible(true);

         */
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtnombreusuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreusuarioMouseMoved

    }//GEN-LAST:event_txtnombreusuarioMouseMoved

    private void txtnombreusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreusuarioMouseClicked
        txtnombreusuario.setText("");
    }//GEN-LAST:event_txtnombreusuarioMouseClicked

    private void txtnombreusuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreusuarioMouseExited
        if (txtnombreusuario.getText().equals("")) {
            txtnombreusuario.setText("Ingrese nombre de usuario");
        }
    }//GEN-LAST:event_txtnombreusuarioMouseExited

    private void txtcontraseñaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcontraseñaMouseMoved

    }//GEN-LAST:event_txtcontraseñaMouseMoved

    private void txtcontraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcontraseñaMouseClicked
        txtcontraseña.setText("");
    }//GEN-LAST:event_txtcontraseñaMouseClicked

    private void txtcontraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcontraseñaMouseExited
        String contra = new String(txtcontraseña.getPassword());
        if (contra.equals("")) {
            txtcontraseña.setText("             ");
        }
    }//GEN-LAST:event_txtcontraseñaMouseExited

    private void jLabel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseMoved
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 35, 18)));
    }//GEN-LAST:event_jLabel9MouseMoved

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        this.setState(Loginv.ICONIFIED);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 235, 239)));
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 35, 18)));
    }//GEN-LAST:event_jLabel10MouseMoved

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "Exit", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 235, 239)));
    }//GEN-LAST:event_jLabel10MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SQLUsuarios modSQL = new SQLUsuarios();
        Usuarios mod = new Usuarios();

        ArrayList<Estados> Esta = modSQL.Estados();
        ArrayList<TipoUsuarios> este = modSQL.TiposUsu();

        String pass = new String(txtcontraseña.getPassword());
        if (!txtnombreusuario.getText().equals("") && !pass.equals("")) {
            String nuvopass = Hash.sha1(pass);
            mod.setNombre_usuario(txtnombreusuario.getText());
            mod.setContraseña(nuvopass);
            if (modSQL.Login(mod)) {
                if (mod.getId_tipo() == este.get(1).getIdEstado()) {
                    PantallaDeCargaGrande f = new PantallaDeCargaGrande();
                    f.setVisible(true);
                    this.setVisible(false);
                    if (mod.getEstadoUsu() == Esta.get(1).getIdEstado()) {
                        JOptionPane.showMessageDialog(null, "Te encuentras en estado inactivo \n"
                                + "Contacta a un administrados para mas información");
                        this.setVisible(false);
                    } else {
                        if (!modSQL.RegeistrarEntreda(mod)) {
                            JOptionPane.showMessageDialog(null, "Error en la base de datos");
                        }
                        
                        IntAdmin vc;
                        vc = new IntAdmin(modSQL, mod);
                        f.dispose();
                        this.dispose();
                        vc.setVisible(true);

                    }

                } else {
                    PantallaDeCargaGrande f = new PantallaDeCargaGrande();
                    f.setVisible(true);
                    this.setVisible(false);
                    if (mod.getEstadoUsu() == Esta.get(1).getIdEstado()) {
                        JOptionPane.showMessageDialog(null, "Te encuentras en estado inactivo \n"
                                + "Contacta a un administrados para mas información");
                        this.setVisible(true);
                    } else {
                        if (!modSQL.RegeistrarEntreda(mod)) {
                            JOptionPane.showMessageDialog(null, "Error en la base de datos");
                            this.setVisible(true);
                        }

                        if (modSQL.BuscarPartida(mod)) {
                            VentanaCliente1 vc;
                            try {
                                vc = new VentanaCliente1(mod, modSQL.CargarDatosInicioCultivos(mod), modSQL,
                                        modSQL.NumeroPartida(mod), modSQL.CultivosCOmpa(),
                                        modSQL.Estados(), modSQL.IDNumeroOfertaDeManda(mod));

                                this.dispose();
                                f.dispose();
                                vc.setVisible(true);

                            } catch (IOException ex) {
                                JOptionPane.showMessageDialog(null, "Error en la conexión");
                                this.setVisible(true);

                            }
                        } else {
                            this.dispose();
                        }

                    }
                }

            } else {
                JOptionPane.showMessageDialog(null, "Error en contraseña o usuario");
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    int xx, yy;
    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed


    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel11MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseDragged

    }//GEN-LAST:event_jLabel11MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginv().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtnombreusuario;
    // End of variables declaration//GEN-END:variables

}
