/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import ConexionBD.Cultivo;
import ConexionBD.SQLUsuarios;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javafx.scene.chart.NumberAxis;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.DefaultXYDataset;
import static proyecto.VentanaCliente1.CultivosCompa;

/**
 *
 * @author Acer Nitro 5
 */
public class pnlGraficas extends javax.swing.JPanel {

    ChartPanel chartPanel1;
    //JFreeChart chart;
    /**
     * Creates new form pnlGraficas
     */
    public static ArrayList<Double> HistorialPrecios = new ArrayList<Double>();

    public static ArrayList<Double> getHistorialPrecios() {
        return HistorialPrecios;
    }

    public JComboBox<String> getComCulti() {
        return ComCulti;
    }

    public void setComCulti(JComboBox<String> ComCulti) {
        this.ComCulti = ComCulti;
    }

    public static void setHistorialPrecios(ArrayList<Double> HistorialPrecios) {
        pnlGraficas.HistorialPrecios = HistorialPrecios;
    }
    private ArrayList<Cultivo> Datos = new ArrayList<Cultivo>();

    public pnlGraficas(ArrayList<Cultivo> Datosss) throws IOException {
        initComponents();
        this.Datos = Datosss;

    }

    public void LLenar() {
        this.ComCulti.removeAll();
        int d = 1;
        for (Cultivo Dato : Datos) {
            this.ComCulti.addItem(Dato.getNombreCultivo() + " " + d);
            d++;
        }
    }

    public ArrayList<Cultivo> getDatos() {
        return Datos;
    }

    public void setDatos(ArrayList<Cultivo> Datos) {
        this.Datos = Datos;
    }

    public void CargarLaVaina() {
        SQLUsuarios modSQL = new SQLUsuarios();

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        double alturaNueva = 0;

        String axu = modSQL.BuscarSemanaMala(Datos.get(this.ComCulti.getSelectedIndex()));
        String[] NSemanas = axu.split("-");
        int ss = 0;
        for (int i = 0; i < Datos.get(this.ComCulti.getSelectedIndex()).getSemana() + 1; i++) {
            if (String.valueOf(i + 1).equals(NSemanas[ss])) {
                dataset.addValue(alturaNueva, Datos.get(this.ComCulti.getSelectedIndex()).getNombreCultivo(), String.valueOf(i));
                if ((ss + 1) != NSemanas.length) {
                    ss++;
                }

            } else {
                dataset.addValue(alturaNueva, Datos.get(this.ComCulti.getSelectedIndex()).getNombreCultivo(), String.valueOf(i));
                alturaNueva = (i + 1) * CultivosCompa.get(Datos.get(this.ComCulti.getSelectedIndex()).getIdCultivo() - 1).getTasacCrsi();
                alturaNueva = Math.round(alturaNueva * 100) / 100d;
            }

        }

        //dataset.addValue(10, "1", "2");
        //dataset.addValue(5, "1", "3");
        JFreeChart chart = ChartFactory.createBarChart("Crecimiento", "Semanas", "Altura", dataset, PlotOrientation.VERTICAL,
                true, true, false);

        chartPanel1 = new ChartPanel(chart, false);
        this.jInternalFrame1.getContentPane().add(chartPanel1);
        this.jInternalFrame1.setVisible(true);
    }

    public void VerTodo() {

        DefaultCategoryDataset dataset1 = new DefaultCategoryDataset();
        int d = 0;
        for (Cultivo Dato : Datos) {

            dataset1.addValue(Dato.getAltura(), Dato.getNombreCultivo() + " " + d, Dato.getNombreCultivo() + "  " + d);
            d++;
        }

        //dataset.addValue(10, "1", "2");
        //dataset.addValue(5, "1", "3");
        JFreeChart chart = ChartFactory.createBarChart("Crecimiento", "Nombres", "Altura", dataset1, PlotOrientation.VERTICAL,
                true, true, false);

        this.jInternalFrame1.setVisible(false);
        chartPanel1 = new ChartPanel(chart, false);
        this.jInternalFrame1.getContentPane().remove(0);
        this.jInternalFrame1.getContentPane().add(chartPanel1);
        this.jInternalFrame1.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ComCulti = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(184, 242, 190));
        setVerifyInputWhenFocusTarget(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jInternalFrame1.setBorder(null);
        jInternalFrame1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jInternalFrame1.setEnabled(false);
        jInternalFrame1.setFocusCycleRoot(false);
        jInternalFrame1.setFocusable(false);
        jInternalFrame1.setVisible(true);
        add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 470));

        jPanel2.setBackground(new java.awt.Color(184, 242, 190));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Cultivos Activos");

        ComCulti.setBackground(new java.awt.Color(184, 242, 190));
        ComCulti.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jButton2.setBackground(new java.awt.Color(184, 242, 190));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton2.setText("Ver todas las plantas");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(184, 242, 190));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Ver evolución");
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComCulti, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ComCulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 170, 470));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intAdmin/FondoAdmin.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 750, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        SQLUsuarios modSQL = new SQLUsuarios();
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        double alturaNueva = 0;

        String axu = modSQL.BuscarSemanaMala(Datos.get(this.ComCulti.getSelectedIndex()));
        String[] NSemanas = axu.split("-");
        int ss = 0;
        for (int i = 0; i < Datos.get(this.ComCulti.getSelectedIndex()).getSemana() + 1; i++) {
            if (String.valueOf(i + 1).equals(NSemanas[ss])) {
                dataset.addValue(alturaNueva, Datos.get(this.ComCulti.getSelectedIndex()).getNombreCultivo(), String.valueOf(i));
                if ((ss + 1) != NSemanas.length) {
                    ss++;
                }
            } else {
                dataset.addValue(alturaNueva, Datos.get(this.ComCulti.getSelectedIndex()).getNombreCultivo(), String.valueOf(i));
                alturaNueva = (i + 1) * CultivosCompa.get(Datos.get(this.ComCulti.getSelectedIndex()).getIdCultivo() - 1).getTasacCrsi();
                alturaNueva = Math.round(alturaNueva * 100) / 100d;
            }

        }
        JFreeChart chart = ChartFactory.createBarChart("Crecimiento", "Semanas", "Altura", dataset, PlotOrientation.VERTICAL,
                true, true, false);
        this.jInternalFrame1.setVisible(false);
        chartPanel1 = new ChartPanel(chart, false);
        this.jInternalFrame1.getContentPane().remove(0);
        this.jInternalFrame1.getContentPane().add(chartPanel1);
        this.jInternalFrame1.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.VerTodo();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> ComCulti;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
