/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import ConexionBD.SQLUsuarios;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer Nitro 5
 */
public class pnlInformes extends javax.swing.JPanel {

    /**
     * Creates new form pnlInformes
     */
    SQLUsuarios modsql = new SQLUsuarios();

    public pnlInformes() {
        initComponents();
        String[] columnNames = {"Nombre", "Apellido", "Numero celular", "Correo", "Nombre Usuario", "Fecha/Hora de registro"};
        Object[][] datosv = modsql.CargarUsuarios();
        DefaultTableModel dtm = new DefaultTableModel(datosv, columnNames);
        this.TablaSql.setModel(dtm);
        this.TablaSql.setBackground(new Color(184, 242, 190));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSql = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        TxtVatriable = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ComBoxSql2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(69, 191, 85));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 242, 190)));

        TablaSql.setBackground(new java.awt.Color(184, 242, 190));
        TablaSql.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TablaSql.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaSql.setGridColor(new java.awt.Color(184, 242, 190));
        TablaSql.setRowHeight(22);
        jScrollPane1.setViewportView(TablaSql);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 730, 560));

        jPanel2.setBackground(new java.awt.Color(151, 237, 138));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtVatriable.setBackground(new java.awt.Color(184, 242, 190));
        TxtVatriable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TxtVatriable.setBorder(null);
        jPanel2.add(TxtVatriable, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intAdmin/lupa.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 50, 50));

        ComBoxSql2.setBackground(new java.awt.Color(184, 242, 190));
        ComBoxSql2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComBoxSql2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ver Cultivos de un cliente", "Ver la producción de un cliente", "<html>Ver los registros de entrada y salida de un cliente</html>" }));
        ComBoxSql2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ComBoxSql2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComBoxSql2ActionPerformed(evt);
            }
        });
        jPanel2.add(ComBoxSql2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 270, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("<html>Ingresa el usuario a buscar:</html>");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 140, 70));

        jButton1.setBackground(new java.awt.Color(151, 237, 138));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(151, 237, 138)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 100, 30));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Ver Clientes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void ComBoxSql2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComBoxSql2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComBoxSql2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int index = ComBoxSql2.getSelectedIndex();
        switch (index) {
            case 0:
                String[] columnNames = {"Nombre del cultivo", "Semana", "Altura cultivo", "Agua gastada", "Estado"};
                if (this.TxtVatriable.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Ingrese un usuario a buscar");
                } else {
                    if (modsql.VerificarNombre(this.TxtVatriable.getText())) {
                        Object[][] datosv = modsql.CargarUsuariosCultivos(this.TxtVatriable.getText());
                        DefaultTableModel dtm = new DefaultTableModel(datosv, columnNames);
                        this.TablaSql.setModel(dtm);
                        this.TablaSql.setBackground(new Color(184, 242, 190));
                    } else {
                        JOptionPane.showMessageDialog(null, "Usuario no encontrado");
                    }

                }
                break;
            case 1:
                String[] columnNames1 = {"Cantidad de ventas", "Capital total", "cantidad de prouctos acomulados"};
                if (this.TxtVatriable.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Ingrese un usuario a buscar");
                } else {
                    if (modsql.VerificarNombre(this.TxtVatriable.getText())) {
                        Object[][] datosv = modsql.CargarUsuariosProceso(this.TxtVatriable.getText());
                        DefaultTableModel dtm = new DefaultTableModel(datosv, columnNames1);
                        this.TablaSql.setModel(dtm);
                        this.TablaSql.setBackground(new Color(184, 242, 190));
                    } else {
                        JOptionPane.showMessageDialog(null, "Usuario no encontrado");
                    }

                }
                break;
            case 2:
                String[] columnNames2 = {"Entradas", "Salidas"};
                if (this.TxtVatriable.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Ingrese un usuario a buscar");
                } else {
                    if (modsql.VerificarNombre(this.TxtVatriable.getText())) {
                        Object[][] datosv = modsql.CargarUsuariosRegsitros(this.TxtVatriable.getText());
                        DefaultTableModel dtm = new DefaultTableModel(datosv, columnNames2);
                        this.TablaSql.setModel(dtm);
                        this.TablaSql.setBackground(new Color(184, 242, 190));
                    } else {
                        JOptionPane.showMessageDialog(null, "Usuario no encontrado");
                    }

                }

                break;
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String[] columnNames = {"Nombre", "Apellido", "Numero celular", "Correo", "Nombre Usuario", "Fecha/Hora de registro"};
        Object[][] datosv = modsql.CargarUsuarios();
        DefaultTableModel dtm = new DefaultTableModel(datosv, columnNames);
        this.TablaSql.setModel(dtm);
        this.TablaSql.setBackground(new Color(184, 242, 190));
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComBoxSql2;
    private javax.swing.JTable TablaSql;
    private javax.swing.JTextField TxtVatriable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
