/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import ConexionBD.Hash;
import ConexionBD.SQLUsuarios;
import ConexionBD.Usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer Nitro 5
 */
public class pnlRegistro extends javax.swing.JPanel {

    /**
     * Creates new form pnlRegistro
     */
    public pnlRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumeroCelular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        TipoUsu = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        EstadoUsuBox = new javax.swing.JComboBox<>();
        txtContraseña = new javax.swing.JPasswordField();
        txtConfirmarContraseña = new javax.swing.JPasswordField();
        lbllogo = new javax.swing.JLabel();

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(178, 249, 226));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(217, 24, 114));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(217, 24, 114));
        jLabel4.setText("Nombres:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtNombres.setBackground(new java.awt.Color(178, 249, 226));
        txtNombres.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtNombres.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 170, 30));

        jLabel1.setBackground(new java.awt.Color(217, 24, 114));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(217, 24, 114));
        jLabel1.setText("Apellidos:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtApellidos.setBackground(new java.awt.Color(178, 249, 226));
        txtApellidos.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtApellidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 170, 30));

        jLabel8.setBackground(new java.awt.Color(217, 24, 114));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(217, 24, 114));
        jLabel8.setText("<html>Numero de celular:</html>");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 40));

        txtNumeroCelular.setBackground(new java.awt.Color(178, 249, 226));
        txtNumeroCelular.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtNumeroCelular.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNumeroCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCelularActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumeroCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 170, 30));

        jLabel5.setBackground(new java.awt.Color(217, 24, 114));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(217, 24, 114));
        jLabel5.setText("Correo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 20));

        txtCorreo.setBackground(new java.awt.Color(178, 249, 226));
        txtCorreo.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 170, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(166, 46, 78));
        jLabel2.setText("Todos los campos son obligatorios");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 270, 20));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 270, 20));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 270, 20));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 270, 20));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 320, 420));

        jPanel2.setBackground(new java.awt.Color(178, 249, 226));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(217, 24, 114));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(217, 24, 114));
        jLabel3.setText("Usuario:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtNombreUsuario.setBackground(new java.awt.Color(178, 249, 226));
        txtNombreUsuario.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtNombreUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 160, 30));

        jLabel6.setBackground(new java.awt.Color(217, 24, 114));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(217, 24, 114));
        jLabel6.setText("Contraseña:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel7.setBackground(new java.awt.Color(217, 24, 114));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(217, 24, 114));
        jLabel7.setText("<html>Confirmar contraseña:</html>");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intAdmin/registarOFF.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intAdmin/registarON_1.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intAdmin/registarON_1.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intAdmin/registarON_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 140, 50));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 270, 20));

        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 270, 20));

        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 270, 20));

        jLabel13.setBackground(new java.awt.Color(217, 24, 114));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(217, 24, 114));
        jLabel13.setText("Tipo de usuario:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, -1));

        TipoUsu.setBackground(new java.awt.Color(178, 249, 226));
        TipoUsu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TipoUsu.setForeground(new java.awt.Color(217, 24, 114));
        TipoUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Admin" }));
        jPanel2.add(TipoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 130, 20));

        jLabel9.setBackground(new java.awt.Color(217, 24, 114));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(217, 24, 114));
        jLabel9.setText("Estado del usuario:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, -1));

        EstadoUsuBox.setBackground(new java.awt.Color(178, 249, 226));
        EstadoUsuBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        EstadoUsuBox.setForeground(new java.awt.Color(217, 24, 114));
        EstadoUsuBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jPanel2.add(EstadoUsuBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 130, 20));

        txtContraseña.setBackground(new java.awt.Color(178, 249, 226));
        txtContraseña.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 249, 226)));
        jPanel2.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 170, 30));

        txtConfirmarContraseña.setBackground(new java.awt.Color(178, 249, 226));
        txtConfirmarContraseña.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtConfirmarContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(178, 249, 226)));
        jPanel2.add(txtConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 170, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 320, 420));

        lbllogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intAdmin/fondoRegistro.jpg"))); // NOI18N
        lbllogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lbllogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCelularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SQLUsuarios modSQL = new SQLUsuarios();
        Usuarios mod = new Usuarios();
        //Campos a evaluar
        //Se convierte a String
        String contra = new String(txtContraseña.getPassword());
        String contraCon = new String(txtConfirmarContraseña.getPassword());
        if (modSQL.VerificarNombre(txtNombreUsuario.getText())) {
            JOptionPane.showMessageDialog(this, "El usuario " + txtNombreUsuario.getText() + " ya está registrado.\n"
                    + " Ingresa otro usuario.");
        } else {
            if (txtNombres.getText().equals("") || txtApellidos.getText().equals("") || txtNumeroCelular.getText().equals("")
                    || txtCorreo.getText().equals("") || txtNombreUsuario.getText().equals("") || txtConfirmarContraseña.getPassword().equals("")
                    || txtContraseña.getPassword().equals("")) {
                JOptionPane.showMessageDialog(this, "Debes ingresar todos los campos");
            } else {
                try {
                    long f = Long.parseLong(txtNumeroCelular.getText());
                    if (txtCorreo.getText().contains("@")) {
                        if (contra.length() < 8) {
                            JOptionPane.showMessageDialog(this, "La contraseña debe tener mas de 8 caracteres");
                        } else {

                            if (contra.equals(contraCon)) {

                                String nuevaContra = Hash.sha1(contra);
                                mod.setNombres(txtNombres.getText());
                                mod.setApellidos(txtApellidos.getText());
                                mod.setNumero_celular(txtNumeroCelular.getText());
                                mod.setCorreo(txtCorreo.getText());
                                mod.setNombre_usuario(txtNombreUsuario.getText());
                                mod.setContraseña(nuevaContra);
                                mod.setId_tipo((this.TipoUsu.getSelectedIndex() + 1));
                                mod.setEstadoUsu((this.EstadoUsuBox.getSelectedIndex() + 1));

                                if (modSQL.registrar(mod)) {
                                    Limpiar();
                                } else {
                                    JOptionPane.showMessageDialog(this, "Error al registrar.");
                                }

                            } else {
                                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Correo no valido");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Ingrese datos validos");
                }

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Limpiar() {
        txtNombres.setText("");
        txtApellidos.setText("");
        txtNumeroCelular.setText("");
        txtNombreUsuario.setText("");
        txtContraseña.setText("");
        txtConfirmarContraseña.setText("");
        txtCorreo.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EstadoUsuBox;
    private javax.swing.JComboBox<String> TipoUsu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtConfirmarContraseña;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumeroCelular;
    // End of variables declaration//GEN-END:variables
}
