/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import Conexcion.HiloServidor;
import Conexcion.Servidor;
import java.awt.Color;
import java.io.IOException;
import java.net.InetAddress;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Acer
 */
public class VentanaServidor extends javax.swing.JFrame implements Observer {

    private String nombreProductoActual;
    Servidor s;
    HiloServidor h;

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));
    }

    public VentanaServidor() throws IOException {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Recursos/holi.jpeg")).getImage());
        this.AguaLable4.setText(String.valueOf(HiloServidor.Agua));
        this.LabZanahoria.setText(String.valueOf(HiloServidor.Zanahoria));
        this.LabMaiz.setText(String.valueOf(HiloServidor.Maiz));
        this.LabPapa.setText(String.valueOf(HiloServidor.Papa));
        this.LabTomate.setText(String.valueOf(HiloServidor.Tomate));
        setColor(btnbusqueda);
        indbusqueda.setBackground(new Color(39, 86, 43));
        this.setLocationRelativeTo(null);
        s = new Servidor(5000);
        s.addObserver(this);
        Thread t = new Thread(s);
        System.out.println("->>>> " + t.getName());
        t.start();

    }

    public Servidor darservi() {
        return s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AguaLable1 = new javax.swing.JLabel();
        PrecioLabe1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        AguaLable7 = new javax.swing.JLabel();
        LabZanahoria = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        TxtZanahoria = new javax.swing.JTextField();
        AguaLable9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabMaiz = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LabPapa = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LabTomate = new javax.swing.JLabel();
        TxtMaiz = new javax.swing.JTextField();
        TxtPapa = new javax.swing.JTextField();
        TxtTomate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        AguaLable = new javax.swing.JLabel();
        AguaLable4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Txt112 = new javax.swing.JTextField();
        AguaLable2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnbusqueda = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        indbusqueda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agro-Learning-Server");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AguaLable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(AguaLable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 42, -1, -1));

        PrecioLabe1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(PrecioLabe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 106, -1, -1));

        jPanel5.setBackground(new java.awt.Color(194, 221, 199));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AguaLable7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AguaLable7.setText("Zanahoria:");

        LabZanahoria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabZanahoria.setText("0");

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton3.setText("Enviar Información");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        TxtZanahoria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        AguaLable9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AguaLable9.setText("<html>Establecer cambios en los precios</html>");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Maíz:");

        LabMaiz.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabMaiz.setText("0");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Papa:");

        LabPapa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabPapa.setText("0");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Tomate:");

        LabTomate.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabTomate.setText("0");

        TxtMaiz.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        TxtPapa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        TxtTomate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(AguaLable9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AguaLable7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabZanahoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabMaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabPapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabTomate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtZanahoria)
                            .addComponent(TxtMaiz, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(TxtPapa)
                            .addComponent(TxtTomate))))
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AguaLable9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AguaLable7)
                    .addComponent(LabZanahoria)
                    .addComponent(TxtZanahoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LabMaiz)
                    .addComponent(TxtMaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LabPapa)
                    .addComponent(TxtPapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LabTomate)
                    .addComponent(TxtTomate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 370, 390));

        jPanel3.setBackground(new java.awt.Color(194, 221, 199));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AguaLable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AguaLable.setText("Agua:");

        AguaLable4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AguaLable4.setText("0");

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton1.setText("Enviar Información");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Txt112.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        AguaLable2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AguaLable2.setText("<html>Establecer cambios         en el agua</html>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(AguaLable)
                        .addGap(29, 29, 29)
                        .addComponent(AguaLable4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Txt112, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(AguaLable2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AguaLable2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AguaLable)
                    .addComponent(AguaLable4)
                    .addComponent(Txt112, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 370, 390));

        jPanel1.setBackground(new java.awt.Color(0, 38, 28));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnbusqueda.setBackground(new java.awt.Color(0, 38, 28));
        btnbusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnbusquedaMousePressed(evt);
            }
        });
        btnbusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Inicio");
        btnbusqueda.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        indbusqueda.setBackground(new java.awt.Color(0, 38, 28));
        indbusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btnbusqueda.add(indbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 60));

        jPanel1.add(btnbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoicon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 490));

        jPanel2.setBackground(new java.awt.Color(22, 128, 57));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intAdmin/minimizarR.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 60, 50));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intAdmin/cerrarR.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel21MouseMoved(evt);
            }
        });
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 60, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 800, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/intAdmin/FondoAdmin.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 800, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            double dato1;
            dato1 = Double.parseDouble(this.Txt112.getText());
            String[] Stringvalores = {"agua"};
            double[] valores = {dato1};
            s.enviarInfo(Stringvalores, valores);
            HiloServidor.Agua = dato1;
            this.AguaLable4.setText(String.valueOf(HiloServidor.Agua));
            JOptionPane.showMessageDialog(this, "Cambios relizados");
            this.Txt112.setText("");

        } catch (IOException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Datos incorrectos");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnbusquedaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbusquedaMousePressed


    }//GEN-LAST:event_btnbusquedaMousePressed

    int xx, yy;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseMoved

    }//GEN-LAST:event_jLabel21MouseMoved

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "Exit", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited

    }//GEN-LAST:event_jLabel21MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!TxtZanahoria.equals("") && !TxtMaiz.equals("") && !TxtPapa.equals("") && !TxtTomate.equals("")) {

            try {

                double dato1 = Double.parseDouble(this.TxtZanahoria.getText());
                double dato2 = Double.parseDouble(this.TxtMaiz.getText());
                double dato3 = Double.parseDouble(this.TxtPapa.getText());
                double dato4 = Double.parseDouble(this.TxtTomate.getText());
                String[] Stringvalores = {"Zanahoria", "Maíz", "Papa", "Tomate"};
                double[] valores = {dato1, dato2, dato3, dato4};
                s.enviarInfo(Stringvalores, valores);
                HiloServidor.Zanahoria = dato1;
                HiloServidor.Maiz = dato2;
                HiloServidor.Papa = dato3;
                HiloServidor.Tomate = dato4;
                this.LabZanahoria.setText(String.valueOf(HiloServidor.Zanahoria));
                this.LabMaiz.setText(String.valueOf(HiloServidor.Maiz));
                this.LabPapa.setText(String.valueOf(HiloServidor.Papa));
                this.LabTomate.setText(String.valueOf(HiloServidor.Tomate));
                JOptionPane.showMessageDialog(this, "Cambios relizados");
                this.TxtZanahoria.setText("");
                this.TxtMaiz.setText("");
                this.TxtPapa.setText("");
                this.TxtTomate.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Datos incorrectos");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaServidor().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(VentanaServidor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AguaLable;
    private javax.swing.JLabel AguaLable1;
    private javax.swing.JLabel AguaLable2;
    private javax.swing.JLabel AguaLable4;
    private javax.swing.JLabel AguaLable7;
    private javax.swing.JLabel AguaLable9;
    private javax.swing.JLabel LabMaiz;
    private javax.swing.JLabel LabPapa;
    private javax.swing.JLabel LabTomate;
    private javax.swing.JLabel LabZanahoria;
    private javax.swing.JLabel PrecioLabe1;
    private javax.swing.JTextField Txt112;
    private javax.swing.JTextField TxtMaiz;
    private javax.swing.JTextField TxtPapa;
    private javax.swing.JTextField TxtTomate;
    private javax.swing.JTextField TxtZanahoria;
    private javax.swing.JPanel btnbusqueda;
    private javax.swing.JPanel indbusqueda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        /*
        if (arg instanceof Double) {
            this.AguaLable4.setText(String.valueOf(s.RestarAgua((Double) arg)));
        }*/
        if (arg instanceof String) {
            nombreProductoActual = (String) arg;
        } else {
            double valor = (double) arg;
            switch (nombreProductoActual) {
                case "Zanahoria":
                    s.ActilizaPrecio(valor, nombreProductoActual);
                    double a = HiloServidor.Zanahoria;
                    double a1 = HiloServidor.Maiz;
                    double a2 = HiloServidor.Papa;
                    double a3 = HiloServidor.Tomate;
                    a = Math.round(a * 100) / 100d;
                    a1 = Math.round(a1 * 100) / 100d;
                    a2 = Math.round(a2 * 100) / 100d;
                    a3 = Math.round(a3 * 100) / 100d;
                    this.LabZanahoria.setText(String.valueOf(a));
                    this.LabMaiz.setText(String.valueOf(a1));
                    this.LabPapa.setText(String.valueOf(a2));
                    this.LabTomate.setText(String.valueOf(a3));
                    break;
                case "Maíz":
                    s.ActilizaPrecio(valor, nombreProductoActual);
                    double aa = HiloServidor.Zanahoria;
                    double a11 = HiloServidor.Maiz;
                    double a22 = HiloServidor.Papa;
                    double a33 = HiloServidor.Tomate;
                    aa = Math.round(aa * 100) / 100d;
                    a11 = Math.round(a11 * 100) / 100d;
                    a22 = Math.round(a22 * 100) / 100d;
                    a33 = Math.round(a33 * 100) / 100d;
                    this.LabZanahoria.setText(String.valueOf(aa));
                    this.LabMaiz.setText(String.valueOf(a11));
                    this.LabPapa.setText(String.valueOf(a22));
                    this.LabTomate.setText(String.valueOf(a33));
                    break;
                case "Papa":
                    s.ActilizaPrecio(valor, nombreProductoActual);
                    double aaa = HiloServidor.Zanahoria;
                    double a111 = HiloServidor.Maiz;
                    double a222 = HiloServidor.Papa;
                    double a333 = HiloServidor.Tomate;
                    aaa = Math.round(aaa * 100) / 100d;
                    a111 = Math.round(a111 * 100) / 100d;
                    a222 = Math.round(a222 * 100) / 100d;
                    a333 = Math.round(a333 * 100) / 100d;
                    this.LabZanahoria.setText(String.valueOf(aaa));
                    this.LabMaiz.setText(String.valueOf(a111));
                    this.LabPapa.setText(String.valueOf(a222));
                    this.LabTomate.setText(String.valueOf(a333));
                    break;
                case "Tomate":
                    s.ActilizaPrecio(valor, nombreProductoActual);
                    double aaaa = HiloServidor.Zanahoria;
                    double a1111 = HiloServidor.Maiz;
                    double a2222 = HiloServidor.Papa;
                    double a3333 = HiloServidor.Tomate;
                    aaaa = Math.round(aaaa * 100) / 100d;
                    a1111 = Math.round(a1111 * 100) / 100d;
                    a2222 = Math.round(a2222 * 100) / 100d;
                    a3333 = Math.round(a3333 * 100) / 100d;
                    this.LabZanahoria.setText(String.valueOf(aaaa));
                    this.LabMaiz.setText(String.valueOf(a1111));
                    this.LabPapa.setText(String.valueOf(a2222));
                    this.LabTomate.setText(String.valueOf(a3333));
                    break;
                case "agua":
                    this.AguaLable4.setText(String.valueOf(s.RestarAgua((Double) arg)));
                    break;

            }
        }
    }
}
